"""add task_id to docs

Revision ID: f348df8a0d8f
Revises: ea1153d73d1d
Create Date: 2026-04-15 17:09:03.476620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f348df8a0d8f'
down_revision: Union[str, Sequence[str], None] = 'ea1153d73d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'task_id')
    # ### end Alembic commands ###
